services:
  rickrolld:
    image: nugget/rickrolld:latest
    container_name: rickrolld
    restart: unless-stopped
    ports:
      - "23:23"
    networks:
      - default

networks:
  default:
    enable_ipv6: true
